// <auto-generated />
using GovernedAccess.ReferenceAuthority.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GovernedAccess.ReferenceAuthority.Persistence.Migrations
{
    [DbContext(typeof(ReferenceAuthorityDbContext))]
    [Migration("20260825072917_InitialReferenceAuthority")]
    partial class InitialReferenceAuthority
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("GovernedAccess.ReferenceAuthority.Persistence.ReferenceClient", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessApproverPrincipalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("GovernedAccess.ReferenceAuthority.Persistence.ReferenceEnvironmentRole", b =>
                {
                    b.Property<string>("EnvironmentId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrentlyAssignable")
                        .HasColumnType("INTEGER");

                    b.HasKey("EnvironmentId", "RoleId");

                    b.ToTable("EnvironmentRoles", (string)null);
                });

            modelBuilder.Entity("GovernedAccess.ReferenceAuthority.Persistence.ReferenceIncident", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Incidents", (string)null);
                });

            modelBuilder.Entity("GovernedAccess.ReferenceAuthority.Persistence.ReferenceIncidentEnvironmentLink", b =>
                {
                    b.Property<string>("IncidentId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("EnvironmentId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("IncidentId", "EnvironmentId");

                    b.HasIndex("EnvironmentId");

                    b.ToTable("IncidentEnvironmentLinks", (string)null);
                });

            modelBuilder.Entity("GovernedAccess.ReferenceAuthority.Persistence.ReferenceProductionEnvironment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEligibleForIntake")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsProduction")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("ProductionEnvironments", (string)null);
                });

            modelBuilder.Entity("GovernedAccess.ReferenceAuthority.Persistence.ReferenceEnvironmentRole", b =>
                {
                    b.HasOne("GovernedAccess.ReferenceAuthority.Persistence.ReferenceProductionEnvironment", null)
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GovernedAccess.ReferenceAuthority.Persistence.ReferenceIncidentEnvironmentLink", b =>
                {
                    b.HasOne("GovernedAccess.ReferenceAuthority.Persistence.ReferenceProductionEnvironment", null)
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GovernedAccess.ReferenceAuthority.Persistence.ReferenceIncident", null)
                        .WithMany()
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GovernedAccess.ReferenceAuthority.Persistence.ReferenceProductionEnvironment", b =>
                {
                    b.HasOne("GovernedAccess.ReferenceAuthority.Persistence.ReferenceClient", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
