// <auto-generated />
using System;
using GovernedAccess.Workflow.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GovernedAccess.Workflow.Persistence.Persistence.Migrations
{
    [DbContext(typeof(WorkflowDbContext))]
    [Migration("20260827084618_InitialWorkflowPersistence")]
    partial class InitialWorkflowPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("GovernedAccess.Core.Domain.AccessRequests.AccessGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("ActivatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.ToTable("AccessGrants", (string)null);
                });

            modelBuilder.Entity("GovernedAccess.Core.Domain.AccessRequests.AccessRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastModifiedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PersistenceVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PreparationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequesterId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PreparationId")
                        .IsUnique()
                        .HasDatabaseName("UX_AccessRequests_PreparationId");

                    b.HasIndex("RequesterId");

                    b.ToTable("AccessRequests", (string)null);
                });

            modelBuilder.Entity("GovernedAccess.Core.Domain.AccessRequests.ApprovalDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApproverId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("DecidedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApproverId");

                    b.HasIndex("RequestId", "Stage")
                        .IsUnique();

                    b.ToTable("ApprovalDecisions", (string)null);
                });

            modelBuilder.Entity("GovernedAccess.Core.Domain.AccessRequests.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<long>("OccurredAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutcomeCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("RequestId", "OccurredAt", "Id");

                    b.ToTable("AuditEvents", (string)null);
                });

            modelBuilder.Entity("GovernedAccess.Core.Domain.AccessRequests.ProvisioningOperation", b =>
                {
                    b.Property<Guid>("RequestId")
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastAttemptAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastOutcomeCode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("RequestId");

                    b.ToTable("ProvisioningOperations", (string)null);
                });

            modelBuilder.Entity("GovernedAccess.Workflow.Persistence.RequestPreparationRecord", b =>
                {
                    b.Property<Guid>("PreparationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChannelActorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClarificationJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConversationId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnvironmentId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("IncidentId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Justification")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Lifecycle")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaterialChangeAttributionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PredecessorPreparationId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ReadyAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ReadyDeadline")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequesterId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long?>("TerminalAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("PreparationId");

                    b.HasIndex("PredecessorPreparationId");

                    b.HasIndex("RequesterId");

                    b.HasIndex("Channel", "TenantId", "ChannelActorId", "ConversationId", "RequesterId")
                        .IsUnique()
                        .HasDatabaseName("UX_RequestPreparations_ActiveBinding")
                        .HasFilter("\"Lifecycle\" IN ('Collecting', 'Ready')");

                    b.ToTable("RequestPreparations", (string)null);
                });

            modelBuilder.Entity("GovernedAccess.Workflow.Persistence.WorkflowPrincipalRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AuthenticatedPrincipals", (string)null);
                });

            modelBuilder.Entity("GovernedAccess.Core.Domain.AccessRequests.AccessGrant", b =>
                {
                    b.HasOne("GovernedAccess.Core.Domain.AccessRequests.AccessRequest", null)
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GovernedAccess.Core.Domain.AccessRequests.ProvisioningOperation", null)
                        .WithOne()
                        .HasForeignKey("GovernedAccess.Core.Domain.AccessRequests.AccessGrant", "RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GovernedAccess.Core.Domain.AccessRequests.AccessRequest", b =>
                {
                    b.HasOne("GovernedAccess.Workflow.Persistence.WorkflowPrincipalRecord", null)
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("GovernedAccess.Core.Domain.AccessRequests.ValidatedRequestDetails", "Details", b1 =>
                        {
                            b1.Property<Guid>("AccessRequestId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ClientId")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("ClientId");

                            b1.Property<string>("EnvironmentId")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("EnvironmentId");

                            b1.Property<string>("IncidentId")
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("IncidentId");

                            b1.Property<string>("Justification")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("TEXT")
                                .HasColumnName("Justification");

                            b1.Property<string>("RoleId")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("RequestedRoleId");

                            b1.HasKey("AccessRequestId");

                            b1.ToTable("AccessRequests");

                            b1.WithOwner()
                                .HasForeignKey("AccessRequestId");
                        });

                    b.Navigation("Details")
                        .IsRequired();
                });

            modelBuilder.Entity("GovernedAccess.Core.Domain.AccessRequests.ApprovalDecision", b =>
                {
                    b.HasOne("GovernedAccess.Workflow.Persistence.WorkflowPrincipalRecord", null)
                        .WithMany()
                        .HasForeignKey("ApproverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GovernedAccess.Core.Domain.AccessRequests.AccessRequest", null)
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GovernedAccess.Core.Domain.AccessRequests.AuditEvent", b =>
                {
                    b.HasOne("GovernedAccess.Workflow.Persistence.WorkflowPrincipalRecord", null)
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GovernedAccess.Core.Domain.AccessRequests.AccessRequest", null)
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GovernedAccess.Core.Domain.AccessRequests.ProvisioningOperation", b =>
                {
                    b.HasOne("GovernedAccess.Core.Domain.AccessRequests.AccessRequest", null)
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GovernedAccess.Workflow.Persistence.RequestPreparationRecord", b =>
                {
                    b.HasOne("GovernedAccess.Workflow.Persistence.RequestPreparationRecord", null)
                        .WithMany()
                        .HasForeignKey("PredecessorPreparationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GovernedAccess.Workflow.Persistence.WorkflowPrincipalRecord", null)
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
