// <auto-generated />
using System;
using GovernedAccess.Workflow.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GovernedAccess.Workflow.Persistence.Persistence.Migrations
{
    [DbContext(typeof(WorkflowDbContext))]
    partial class WorkflowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("GovernedAccess.Workflow.Persistence.RequestPreparationRecord", b =>
                {
                    b.Property<Guid>("PreparationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CandidateVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChannelActorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClarificationJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConversationId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnvironmentId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("IncidentId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("InterpretedTurnCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Justification")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Lifecycle")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaterialChangeAttributionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PredecessorPreparationId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ReadyAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ReadyDeadline")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequesterId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long?>("TerminalAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("PreparationId");

                    b.HasIndex("PredecessorPreparationId");

                    b.HasIndex("RequesterId");

                    b.HasIndex("Channel", "TenantId", "ChannelActorId", "ConversationId", "RequesterId")
                        .IsUnique()
                        .HasDatabaseName("UX_RequestPreparations_ActiveBinding")
                        .HasFilter("\"Lifecycle\" IN ('Collecting', 'Ready')");

                    b.ToTable("RequestPreparations", (string)null);
                });

            modelBuilder.Entity("GovernedAccess.Workflow.Persistence.WorkflowPrincipalRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AuthenticatedPrincipals", (string)null);
                });

            modelBuilder.Entity("GovernedAccess.Workflow.Persistence.RequestPreparationRecord", b =>
                {
                    b.HasOne("GovernedAccess.Workflow.Persistence.RequestPreparationRecord", null)
                        .WithMany()
                        .HasForeignKey("PredecessorPreparationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GovernedAccess.Workflow.Persistence.WorkflowPrincipalRecord", null)
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
